### PR TITLE
Updated code for node v4 compilation

### PR DESCRIPTION
**Pull request by ldiqual**
@hulbert

Compiles on node v4.2.2.

Build instructions:

```
$ nvm install v4.2.2
$ nvm use v4.2.2
$ npm install node-gyp
$ ./node_modules/.bin/node-gyp configure
$ ./node_modules/.bin/node-gyp build
```

Major steps used to convert to node v4:
- Updated to nan 2.1.0
- Used this script https://github.com/nodejs/nan/issues/376#issuecomment-120838432 to convert most of the codebase
- Most nan values were `MaybeLocal` instead of `Local` (which is kind of an optional -- see https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_maybe_local), force converted them to `Local` with `ToLocalChecked()` (unsafe).
- `args` was renamed to `info`
- Rest was just a matter of reading more nan doc

### CODE REVIEW

**Comment by hulbert** [comment]
@ldiqual awesome! Thanks for tackling this.

> Most nan values were MaybeLocal instead of Local (which is kind of an optional -- see https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_maybe_local), force converted them to Local with ToLocalChecked() (unsafe).

Any risk on this change to things crashing?

**Comment by ldiqual** [comment]
@hulbert My guess is that the behavior doesn't change between then and now: if you can't get a local handle, then it crashes. The new behavior of nan makes it so you have to unwrap the optional, the previous behavior produced an "implicit" optional (which would fail with a null reference if used). That's only my guess, my v8 and c++ skills are really rusty.

Ultimately, we'll want the original author of the library to confirm this.

**Comment by jdsadow** [comment]
@ldiqual @hulbert what's the status on this, guys?

**Comment by hulbert** [comment]
@jdsadow will discuss in Trello

**Comment by rregue** [comment]
I think we should close this.

**Pull request closed without merging**
